version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=default
      - DB_PASSWORD=secret
      - DB_NAME=task-management
      - JWT_SECRET=your-secret-key-change-in-production
      - JWT_EXPIRATION=24h
      - ENV=development
    volumes:
      - ./config:/app/config
    restart: on-failure

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=task-management
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: always

volumes:
  postgres-data: 