# Server Configuration
server:
  port: 8080
  timeout: 10s
  read_timeout: 5s
  write_timeout: 10s
  shutdown_timeout: 30s

# Database Configuration
database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  user: ${DB_USER:default}
  password: ${DB_PASSWORD:secret}
  name: ${DB_NAME:task-management}
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Authentication Configuration
auth:
  jwt_secret: ${JWT_SECRET:your-secret-key-change-in-production}
  jwt_expiration: ${JWT_EXPIRATION:24h}
  bcrypt_cost: 12

# Logging Configuration
logging:
  level: ${LOG_LEVEL:info}
  format: ${LOG_FORMAT:json}

casbin:
  model_path: "config/rbac_model.conf"
  policy_path: "config/rbac_policy.csv"
  auto_load: true
  auto_save: true 
# Environment
env: ${ENV:development} 
